spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/REST
    username: root
    password: [yourpassword]

mybatis:
  type-aliases-package: com.lichen.restfullearning.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    name: ./log/pro/rest-pro.log
  level:
    root: info
    com.lichen: info